title: "Siwon Ryu"
author: "Siwon Ryu"
#description: "ab"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
encoding: "UTF-8"
robots: noindex

# Layout
show_excerpts: true        # show article excerpts on the home page
minimal: false             # use a dark header

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}



#include:
# - _pages

collections:
  pages:
    output: true
  assets:
    output: true


#url: "https://siwonryu.github.io/WP_tmp"
url: "https://siwonryu.com"